graph TD
  route_donutAuthorize_pages_miniProgramLoginAuthorize_miniProgramLoginAuthorize["donutAuthorize__/pages/miniProgramLoginAuthorize/miniProgramLoginAuthorize"]
  route_pages_admin_checkin_list_index["pages/admin/checkin/list/index"]
  route_pages_admin_checkin_manage_index["pages/admin/checkin/manage/index"]
  route_pages_admin_index["pages/admin/index"]
  route_pages_admin_user_profile_index["pages/admin/user/profile/index"]
  route_pages_app_iap_index["pages/app/iap/index"]
  route_pages_app_login_index["pages/app/login/index"]
  route_pages_app_native_login_index["pages/app/native-login/index"]
  route_pages_app_pay_index["pages/app/pay/index"]
  route_pages_audio_detail_index["pages/audio/detail/index"]
  route_pages_audio_index_index["pages/audio/index/index"]
  route_pages_audio_list_index["pages/audio/list/index"]
  route_pages_checkin_comment_index["pages/checkin/comment/index"]
  route_pages_checkin_help_index["pages/checkin/help/index"]
  route_pages_checkin_history_index["pages/checkin/history/index"]
  route_pages_checkin_index_index["pages/checkin/index/index"]
  route_pages_checkin_my_index["pages/checkin/my/index"]
  route_pages_correction_session_detail["pages/correction/session/detail"]
  route_pages_correction_sessions_index["pages/correction/sessions/index"]
  route_pages_correction_student_bind_index["pages/correction/student/bind/index"]
  route_pages_correction_student_errors_detail_index["pages/correction/student/errors/detail/index"]
  route_pages_correction_student_errors_index["pages/correction/student/errors/index"]
  route_pages_correction_student_errors_list_index["pages/correction/student/errors/list/index"]
  route_pages_correction_student_errors_tags_detail_index["pages/correction/student/errors/tags/detail/index"]
  route_pages_correction_student_errors_tags_index["pages/correction/student/errors/tags/index"]
  route_pages_correction_teacher_students_bind_index["pages/correction/teacher/students/bind/index"]
  route_pages_correction_teacher_students_checkins_index["pages/correction/teacher/students/checkins/index"]
  route_pages_correction_teacher_students_detail_index["pages/correction/teacher/students/detail/index"]
  route_pages_correction_teacher_students_index["pages/correction/teacher/students/index"]
  route_pages_correction_teacher_wallet_index["pages/correction/teacher/wallet/index"]
  route_pages_feedback_detail_index["pages/feedback/detail/index"]
  route_pages_feedback_index_index["pages/feedback/index/index"]
  route_pages_feedback_list_index["pages/feedback/list/index"]
  route_pages_index_index["pages/index/index"]
  route_pages_learning_base_beginner_detail_index["pages/learning/base/beginner/detail/index"]
  route_pages_learning_base_beginner_list_index["pages/learning/base/beginner/list/index"]
  route_pages_learning_base_jyutping_index["pages/learning/base/jyutping/index"]
  route_pages_learning_books_hambaanglaang_detail_index["pages/learning/books/hambaanglaang/detail/index"]
  route_pages_learning_books_hambaanglaang_index_index["pages/learning/books/hambaanglaang/index/index"]
  route_pages_learning_crat_article_test_index["pages/learning/crat/article-test/index"]
  route_pages_learning_crat_article_index["pages/learning/crat/article/index"]
  route_pages_learning_crat_char_bucket_index["pages/learning/crat/char-bucket/index"]
  route_pages_learning_crat_char_index["pages/learning/crat/char/index"]
  route_pages_learning_crat_index["pages/learning/crat/index"]
  route_pages_learning_crat_test_index["pages/learning/crat/test/index"]
  route_pages_learning_crat_word_bucket_index["pages/learning/crat/word-bucket/index"]
  route_pages_learning_crat_word_index["pages/learning/crat/word/index"]
  route_pages_learning_lessons_top_zi_detail_index["pages/learning/lessons/top/zi/detail/index"]
  route_pages_learning_lessons_top_zi_index_index["pages/learning/lessons/top/zi/index/index"]
  route_pages_learning_lessons_zi_detail_index["pages/learning/lessons/zi/detail/index"]
  route_pages_learning_lessons_zi_index_index["pages/learning/lessons/zi/index/index"]
  route_pages_learning_lessons_zi_slide_index["pages/learning/lessons/zi/slide/index"]
  route_pages_my_account_index["pages/my/account/index"]
  route_pages_my_audio_setting_index["pages/my/audio-setting/index"]
  route_pages_my_favorites_index["pages/my/favorites/index"]
  route_pages_my_history_index["pages/my/history/index"]
  route_pages_my_index_index["pages/my/index/index"]
  route_pages_my_msg_index["pages/my/msg/index"]
  route_pages_my_notification_detail_index["pages/my/notification/detail/index"]
  route_pages_my_notification_index["pages/my/notification/index"]
  route_pages_my_pinyin_style_index["pages/my/pinyin-style/index"]
  route_pages_my_pinyin_index["pages/my/pinyin/index"]
  route_pages_my_sound_index["pages/my/sound/index"]
  route_pages_my_user_setting["pages/my/user/setting"]
  route_pages_order_list_index["pages/order/list/index"]
  route_pages_pay_agreement_index["pages/pay/agreement/index"]
  route_pages_pay_redeem_claim_index["pages/pay/redeem-claim/index"]
  route_pages_pay_redeem_index["pages/pay/redeem/index"]
  route_pages_pay_vip_index["pages/pay/vip/index"]
  route_pages_poetry_detail_index["pages/poetry/detail/index"]
  route_pages_songs_detail_index["pages/songs/detail/index"]
  route_pages_songs_list_index["pages/songs/list/index"]
  route_pages_songs_search_index["pages/songs/search/index"]
  route_pages_sph_index["pages/sph/index"]
  route_pages_tools_comment_tools_index["pages/tools/comment-tools/index"]
  route_pages_tools_jyutping_index["pages/tools/jyutping/index"]
  route_pages_tools_text_to_jyutping_detail_index["pages/tools/text-to-jyutping/detail/index"]
  route_pages_tools_text_to_jyutping_export_records_index["pages/tools/text-to-jyutping/export-records/index"]
  route_pages_tools_text_to_jyutping_index_index["pages/tools/text-to-jyutping/index/index"]
  route_pages_tools_text_to_jyutping_list_index["pages/tools/text-to-jyutping/list/index"]
  route_pages_tools_text_to_jyutping_preview_index["pages/tools/text-to-jyutping/preview/index"]
  route_pages_tools_text_to_speech_index["pages/tools/text-to-speech/index"]
  route_pages_tools_translate_favorites_list["pages/tools/translate/favorites/list"]
  route_pages_tools_translate_index["pages/tools/translate/index"]
  route_pages_tools_vocab_notebook_add_index["pages/tools/vocab-notebook/add/index"]
  route_pages_tools_vocab_notebook_category_manage_index["pages/tools/vocab-notebook/category-manage/index"]
  route_pages_tools_vocab_notebook_edit_index["pages/tools/vocab-notebook/edit/index"]
  route_pages_tools_vocab_notebook_index["pages/tools/vocab-notebook/index"]
  route_pages_tools_vocab_notebook_list_index["pages/tools/vocab-notebook/list/index"]
  route_pages_video_detail_index["pages/video/detail/index"]
  route_pages_video_list_index["pages/video/list/index"]
  route_pages_vocabulary_detail_index["pages/vocabulary/detail/index"]
  route_pages_voice_detail_index["pages/voice/detail/index"]
  route_pages_voice_index_index["pages/voice/index/index"]
  route_pages_webview_index["pages/webview/index"]
  route_dynamic_pages_app_iap_index_navigateTo_t_navTo["[dynamic] t"]
  route_pages_app_iap_index -.->|navigateTo / navTo| route_dynamic_pages_app_iap_index_navigateTo_t_navTo
  route_dynamic_pages_app_login_index_navigateTo_n_onShowAgreement["[dynamic] n"]
  route_pages_app_login_index -.->|navigateTo / onShowAgreement| route_dynamic_pages_app_login_index_navigateTo_n_onShowAgreement
  route_pages_app_login_index -.->|navigateTo / huaweiLogin| route_pages_webview_index
  route_pages_app_pay_index -->|reLaunch / onLoad| route_pages_index_index
  route_pages_app_pay_index -->|reLaunch / pay| route_pages_index_index
  route_dynamic_pages_app_pay_index_navigateTo_t_navTo["[dynamic] t"]
  route_pages_app_pay_index -.->|navigateTo / navTo| route_dynamic_pages_app_pay_index_navigateTo_t_navTo
  route_dynamic_pages_audio_index_index_navigateTo_o_navToList["[dynamic] o"]
  route_pages_audio_index_index -.->|navigateTo / navToList| route_dynamic_pages_audio_index_index_navigateTo_o_navToList
  route_dynamic_pages_audio_list_index_navigateTo_i_navToDetail["[dynamic] i"]
  route_pages_audio_list_index -.->|navigateTo / navToDetail| route_dynamic_pages_audio_list_index_navigateTo_i_navToDetail
  route_dynamic_pages_index_index_navigateTo_e_path_noticeClickHandler["[dynamic] e.path"]
  route_pages_index_index -.->|navigateTo / noticeClickHandler| route_dynamic_pages_index_index_navigateTo_e_path_noticeClickHandler
  route_pages_video_list_index -.->|navigateTo / navToDetail| route_pages_video_detail_index
  route_pages_vocabulary_detail_index -.->|navigateTo / navToNotebookAdd| route_pages_tools_vocab_notebook_add_index
  route_pages_voice_index_index -.->|navigateTo / navToDetail| route_pages_voice_detail_index
  route_chunk_0_appservice["chunk_0.appservice (orphan)"]
  route_chunk_1_appservice["chunk_1.appservice (orphan)"]
  route_chunk_66_appservice["chunk_66.appservice (orphan)"]
  route_chunk_67_appservice["chunk_67.appservice (orphan)"]
  route_chunk_68_appservice["chunk_68.appservice (orphan)"]
  route_chunk_69_appservice["chunk_69.appservice (orphan)"]
  route_chunk_70_appservice["chunk_70.appservice (orphan)"]
  route_chunk_71_appservice["chunk_71.appservice (orphan)"]
  route_chunk_72_appservice["chunk_72.appservice (orphan)"]
  route_chunk_73_appservice["chunk_73.appservice (orphan)"]
  route_chunk_74_appservice["chunk_74.appservice (orphan)"]
  route_chunk_75_appservice["chunk_75.appservice (orphan)"]
  route_chunk_76_appservice["chunk_76.appservice (orphan)"]
  route_chunk_77_appservice["chunk_77.appservice (orphan)"]
  route_chunk_78_appservice["chunk_78.appservice (orphan)"]
  route_chunk_79_appservice["chunk_79.appservice (orphan)"]
